name: DreamSpace
version: '1.0-SNAPSHOT'
main: dev.relaxertime.dreamSpace.DreamSpace
api-version: '1.20'
depend: [ ProtocolLib, Citizens, Oraxen]
commands:
  ac:
    description: gfd
  ah:
    description: gdd
  report:
    description: gdd
  unique:
    description: fdd